
deployments:
  - name: dex
    enabled: true
    component: dex
    namespace: dex

  - name: minio
    enabled: true
    component: minio
    namespace: minio
    dependsOn:
      - deployment: ingress-nginx
        module: main
    modules:
      - name: main
        values:
          buckets:
            - name: bucket1
            - name: bucket2
              policy: none
              purge: false
              versioning: false
              objectlocking: false